W Query dynamic range failed. Ret code: RKNN_ERR_MODEL_INVALID. (If it is a static shape RKNN model, please ignore the above warning message.)
W Query dynamic range failed. Ret code: RKNN_ERR_MODEL_INVALID. (If it is a static shape RKNN model, please ignore the above warning message.)
E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/.venv/lib/python3.11/site-packages/rknnlite/api/rknn_lite.py", line 209, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1082, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

I RKNN: [15:01:33.767] RKNN Runtime Information, librknnrt version: 2.3.0 (c949ad889d@2024-11-07T11:35:33)
I RKNN: [15:01:33.767] RKNN Driver Information, version: 0.9.8
I RKNN: [15:01:33.768] RKNN Model Information, version: 6, toolkit version: 2.3.2(compiler version: 2.3.2 (e045de294f@2025-04-07T19:48:25)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
W RKNN: [15:01:33.783] query RKNN_QUERY_INPUT_DYNAMIC_RANGE error, rknn model is static shape type, please export rknn with dynamic_shapes
I RKNN: [15:01:33.909] RKNN Runtime Information, librknnrt version: 2.3.0 (c949ad889d@2024-11-07T11:35:33)
I RKNN: [15:01:33.909] RKNN Driver Information, version: 0.9.8
I RKNN: [15:01:33.909] RKNN Model Information, version: 6, toolkit version: 2.3.2(compiler version: 2.3.2 (e045de294f@2025-04-07T19:48:25)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
W RKNN: [15:01:33.974] query RKNN_QUERY_INPUT_DYNAMIC_RANGE error, rknn model is static shape type, please export rknn with dynamic_shapes
Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/src/app.py", line 106, in _process_frame
    faces_feats = self.engine.detect_and_extract(frame, top_k=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 43, in detect_and_extract
    feats = [self.face_feature_extract(frame_bgr, f) for f in faces]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 43, in <listcomp>
    feats = [self.face_feature_extract(frame_bgr, f) for f in faces]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 34, in face_feature_extract
    return self.recognizer.get(frame_bgr, face.kps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/recognizer.py", line 57, in get
    emb = self.rknn.inference(inputs=[face])[0][0]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/.venv/lib/python3.11/site-packages/rknnlite/api/rknn_lite.py", line 209, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1082, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/src/app.py", line 106, in _process_frame
    faces_feats = self.engine.detect_and_extract(frame, top_k=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 43, in detect_and_extract
    feats = [self.face_feature_extract(frame_bgr, f) for f in faces]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 43, in <listcomp>
    feats = [self.face_feature_extract(frame_bgr, f) for f in faces]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 34, in face_feature_extract
    return self.recognizer.get(frame_bgr, face.kps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/recognizer.py", line 57, in get
    emb = self.rknn.inference(inputs=[face])[0][0]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/.venv/lib/python3.11/site-packages/rknnlite/api/rknn_lite.py", line 209, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1082, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/src/app.py", line 106, in _process_frame
    faces_feats = self.engine.detect_and_extract(frame, top_k=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 43, in detect_and_extract
    feats = [self.face_feature_extract(frame_bgr, f) for f in faces]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 43, in <listcomp>
    feats = [self.face_feature_extract(frame_bgr, f) for f in faces]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 34, in face_feature_extract
    return self.recognizer.get(frame_bgr, face.kps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/recognizer.py", line 57, in get
    emb = self.rknn.inference(inputs=[face])[0][0]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/.venv/lib/python3.11/site-packages/rknnlite/api/rknn_lite.py", line 209, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1082, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/src/app.py", line 106, in _process_frame
    faces_feats = self.engine.detect_and_extract(frame, top_k=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 43, in detect_and_extract
    feats = [self.face_feature_extract(frame_bgr, f) for f in faces]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 43, in <listcomp>
    feats = [self.face_feature_extract(frame_bgr, f) for f in faces]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/engine.py", line 34, in face_feature_extract
    return self.recognizer.get(frame_bgr, face.kps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vicharak/kcc-attendance/src/recognizer.py", line 57, in get
    emb = self.rknn.inference(inputs=[face])[0][0]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/vicharak/kcc-attendance/.venv/lib/python3.11/site-packages/rknnlite/api/rknn_lite.py", line 209, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1082, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.
